### ISSUE TITLE
Cannot read "options" of undefined

### ISSUE THREAD

**Issue by styonsk** [ClaraStream/elasticgoose#1]
I kept getting this error when trying to move documents to elastic search. the error originates from elasticgoose.js around line 355: 

var self = this;

```
_getElasticKeysForSchema(schema, function(keys) {
    _createFields(obj, schema, keys, function(fields) {
        self.client.index({
            index: options.index ? options.index : this.options.index,
            type: options.type,
            id: String(obj._id),
            body: fields
        },
        function(err, resp) {
            if (err) self.errorCallback('save operation failed', err);
            else if (!err) self.infoCallback('save operation succeed', resp);
        });
    });
});
```

"this" is null inside of the callback for _getElasticKeysForSchema. I fixed it by changing this.options.index to self.options.index

Is this a bug or is there something wrong with my set up?

**Comment by bthibault** [comment]
No this is a bug. Thanks for the fix. Is it working now ?

**Comment by bthibault** [comment]
this has been fixed. closing out.
